version: '3'
services:
    postgres:
        container_name: turtl-postgres
        build: ./postgres
        expose:
            - "5432"
        volumes:
            - ./pgbackups:/backups
    turtl-node:
        container_name: turtl-node
        depends_on:
            - postgres
        build: ./turtl-node
        ports:
            - "8181:8181"

